name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the tag
        id: get_tag
        run: |
          TAG="${{ github.event.inputs.tag }}"
          # Replace invalid characters with hyphens and convert to lowercase
          TAG=$(echo $TAG | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9.-' '-')
          # Ensure the tag does not end with a hyphen
          TAG=$(echo $TAG | sed 's/-$//')
          echo "Formatted TAG: $TAG"
          echo "::set-output name=tag::$TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yaryabapi:${{ steps.get_tag.outputs.tag }}

      - name: Log out from Docker Hub
        run: docker logout
